export const SELECT_FILTER = 'HOME/SELECT_FILTER';
export type SELECT_FILTER = typeof SELECT_FILTER;

export const SELECT_POST = 'HOME/SELECT_POST';
export type SELECT_POST = typeof SELECT_POST;

// Fetch Items
export const FETCH_ITEM = 'API/FETCH_ITEM';
export type FETCH_ITEM = typeof FETCH_ITEM;

export const FETCH_ITEM_SUCCESS = 'API/FETCH_ITEM_SUCCESS';
export type FETCH_ITEM_SUCCESS = typeof FETCH_ITEM_SUCCESS;

export const FETCH_ITEM_FAILURE = 'API/FETCH_ITEM_FAILURE';
export type FETCH_ITEM_FAILURE = typeof FETCH_ITEM_FAILURE;

export const FETCH_CHILDREN = 'API/FETCH_CHILDREN';
export type FETCH_CHILDREN = typeof FETCH_CHILDREN;